### PR TITLE
Improve downloading log message

### PR DESCRIPTION
**Pull request by hoshinotsuyoshi**
Regarding GitHub Actions log output, the dot was recognized as part of the URL.

dot

404error

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Review by angelapwen — COMMENTED** [review]
Thank you for the contribution @hoshinotsuyoshi ✨  You will need to run `npm run build` in order to regenerate the relevant transpilation files.

**Review by angelapwen — APPROVED** [review]
Looks good! I will turn auto-merge on for when the PR checks pass 🥳

**Comment by aeisenberg** [comment]
The failing `resolve-environment` test recently had some changes. I wonder if something is wrong with the test.

**Comment by angelapwen** [comment]
I think it _should_ be unrelated as the failure is `mv: cannot move 'node_modules' to '../action/node_modules': Permission denied` in the prepare step. I'll re-run.

**Pull request merged**
