### PR TITLE
Add announcement on Node 16 deprecation

### PR DESCRIPTION
**Pull request by angelapwen**
Make the announcement in the [issue](https://github.com/github/codeql-action/issues/1959) visible via the Action changelog and the README. 

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Review by aeisenberg — APPROVED** [review]
Looks good.

One more suggestion. Can we detect when this warning is emitted and emit a second warning pointing to the issue for more information (only if the original warning is also emitted)?

**Comment by angelapwen** [comment]
Thanks!

> One more suggestion. Can we detect when this warning is emitted and emit a second warning pointing to the issue for more information (only if the original warning is also emitted)?

Hm.. that's an interesting idea. I'm not sure actually, I think it will be more clear once the warning is actually emitted. But so far I don't think we've used a mechanism to catch underlying Actions warnings.

**Comment by aeisenberg** [comment]
After the warning starts being emitted, it will be emitted for _every_ workflow run? If so, we can wait until it's emitted and then include a custom warning that links to the issue.

**Comment by angelapwen** [comment]
> After the warning starts being emitted, it will be emitted for _every_ workflow run? If so, we can wait until it's emitted and then include a custom warning that links to the issue.

Yes, I think so — at least that's what I understood from the Changelog post: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Pull request merged**
