### PR TITLE
Remove debugging output

### PR DESCRIPTION
**Pull request by edoardopirovano**
Looks like I accidentally committed some debugging output when I wrote this part of our CI. This PR removes it.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Review by aeisenberg — APPROVED** [review]

**Comment by aeisenberg** [comment]
That's wild. Looks like failures on Python 2 on macos. Rerunning on main to see if this is a general problem: https://github.com/github/codeql-action/actions/runs/1633534088

**Comment by aeisenberg** [comment]
Yep. Same jobs are failing on main. This must be related to some changes to the python 2 version that is bundled in the virtual environment. Will look deeper when I am back at work.

**Comment by edoardopirovano** [comment]
Hmm, strange. I can't imagine this change causing any test failures so it's probably something that is failing on main too. Maybe a change to the Python version in the Mac OS Actions image is causing the test failures?

**Comment by aeisenberg** [comment]
Here is the most recent passing job: https://github.com/github/codeql-action/runs/4668380714?check_suite_focus=true

You can see that the image used in the passing workflow is the same as the one used in the failing workflow. So, it must be some sort of python transitive dependency that has changed.

**Comment by aeisenberg** [comment]
Difference is the version of virtualenv. For [the passing job](https://github.com/github/codeql-action/runs/4668380714?check_suite_focus=true#step:4:222), it is 20.11.2. For [the failing job](https://github.com/github/codeql-action/runs/4681503135?check_suite_focus=true#step:4:223), it is 20.12.1.

So, looks like we need to force virtualenv@20.11.2 for python 2 tests.

**Comment by aeisenberg** [comment]
Let's see if this works. https://github.com/github/codeql-action/pull/862

**Comment by edoardopirovano** [comment]
Sweet, thanks for fixing that!

**Pull request merged**
