### PR TITLE
Re-enable kotlin tests

### PR DESCRIPTION
**Pull request by aeisenberg**
Reverts https://github.com/github/codeql-action/pull/1473

### CODE REVIEW

**Comment by aeisenberg** [comment]
Hmmm...now it's failing, but because there's an even newer version of kotlin. We are going to need to choose a specific version of kotlin based on the version of the CLI.

**Comment by aeisenberg** [comment]
Converting to draft mode since I won't be able to work on this. If someone else wants to pick it up, please do so.

**Review by iamannalynleynes1206 — APPROVED** [review]

**Comment by aeisenberg** [comment]
Not going to be able to get to this.

**Comment by aeisenberg** [comment]
This should now be working properly. The version of kotlin is fixed to 1.8.21. We can consider upgrading the version in the future, or even running against multiple versions if we like.

**Review by angelapwen — APPROVED** [review]
Thanks for getting back to this!! ✨

**Pull request merged**
