### PR TITLE
Update update-dependencies.yml

### PR DESCRIPTION
**Pull request by mervyd**
### Merge / deployment checklist

- [ ] Confirm this change is backwards compatible with existing workflows.
- [ ] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [ ] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Comment by mervyd** [comment]
#1545

**Review by mervyd — COMMENTED** [review]
#1079 Uploading IMG_0290.MOV…

**Comment by mervyd** [comment]
> #1079 Uploading IMG_0290.MOV…

**Comment by aeisenberg** [comment]
Locking this PR since @mervyd is commenting spam. If you are looking to contribute something real, please open a new PR.

**Pull request closed without merging**
