### PR TITLE
Run integration test PR checks nightly

### PR DESCRIPTION
**Pull request by angelapwen**
Scheduled for 5AM UTC. This will assist in catching bugs introduced with new runner images.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Review by aeisenberg — DISMISSED** [review]

**Comment by angelapwen** [comment]
> Oops. Still in draft. Code looks good. Let's :shipit: if everything passes.

I still haven't configured a notification to our team if any of these fail (see backlinked issue). I can do that in a follow-up if we want to start running immediately though.

**Comment by angelapwen** [comment]
Huh... workflow files don't seem to be working with an error message: 

```
Invalid type for `on`
```

I'll look into it but nothing comes top of mind as `schedule` is supported (and we use it elsewhere!)

**Comment by angelapwen** [comment]
PR check failures are now due to upstream (usually transient) `setup-swift` failures.

**Review by aeisenberg — APPROVED** [review]
Looks reasonable. If the failures are transient, I'll leave it up to you if you want to override the failures and merge or re-run later.

**Comment by angelapwen** [comment]
I don't think we have a way to force green on this repo, and I'd rather not make all those checks non-required (and then make them required again later), so I'll wait to re-run.

**Pull request merged**
