### PR TITLE
Use Node.js v16 in all Actions

### PR DESCRIPTION
**Pull request by henrymercer**
Node.js v16 is in active LTS status and is now the default for Actions, so this PR upgrades to it.  This warrants a minor version bump, so we bump the version to v1.1.0.  As a bonus we remove some stub type definitions.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Comment by henrymercer** [comment]
I'll hold off merging this until the next release is out, so this can sit in `main` for a little while before being released to v1.

**Comment by aeisenberg** [comment]
v1.0.32 was just released. Should we merge this one now?

**Comment by henrymercer** [comment]
Rebased on `main`

**Comment by henrymercer** [comment]
Some CI jobs are failing due to the `windows-latest` image migrating to Windows Server 2022.  Will address those in a separate PR.

**Pull request merged**
