### PR TITLE
Move to macos-13 runners

### PR DESCRIPTION
**Pull request by aeisenberg**
Macos-12 runners are deprecated and are refusing to run.

See some of the failures like this one: https://github.com/github/codeql-action/actions/runs/11671821941/job/32499094199?pr=2575

### CODE REVIEW

**Comment by cklin** [comment]
I think we need to update `.github/workflows/codeql.yml` too.

**Comment by aeisenberg** [comment]
Since I removed some checks, the status won't be ready to merge until I update the checks.

**Comment by aeisenberg** [comment]
This was a lot trickier to get working that I was expecting. I _think_ it should pass now. I will update the required checks afterwards.

**Comment by henrymercer** [comment]
#2588 fixes the export file baseline test.

**Comment by aeisenberg** [comment]
Rebasing in order to get a fix for `Export file baseline information` tests.

**Review by henrymercer — APPROVED** [review]
LGTM.  Thanks Andrew!

**Comment by aeisenberg** [comment]
I can now update the required checks and get this merged.

**Pull request merged**
