### PR TITLE
Update bundle to 2.12.4

### PR DESCRIPTION
**Pull request by dbartol**
### Merge / deployment checklist

- [ ] Confirm this change is backwards compatible with existing workflows.
- [ ] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [ ] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Comment by henrymercer** [comment]
I've pushed a fix for a bug in #1527 that meant we passed a `--qlconfig=undefined` argument when there was no qlconfig file.  I've also merged in main to bring in https://github.com/github/codeql-action/pull/1560 which should fix the issues with `setup-swift`.

**Comment by aeisenberg** [comment]
Thanks for the fix, @henrymercer. I've confirmed that it works locally. I created a PR against `main` to fix it there. https://github.com/github/codeql-action/pull/1564

**Review by henrymercer — APPROVED** [review]
(My commits are merged into main so I'm not signing off on my own code)

**Comment by mirabilos** [comment]
> I've pushed a fix for a bug in #1527 that meant we passed a --qlconfig=undefined argument

Erm, yes, I’m running into this because the bundle has been updated (compared to the previous run of the action). But there’s no new release; how do I get the builds working again?

**Comment by mirabilos** [comment]
Ah well, reverting to an earlier version `codeql-bundle-20230105` worked.

**Comment by henrymercer** [comment]
> Erm, yes, I’m running into this because the bundle has been updated (compared to the previous run of the action). But there’s no new release; how do I get the builds working again?

Hi @mirabilos — this fix was released in version [2.2.6](https://github.com/github/codeql-action/releases/tag/v2.2.6) of the CodeQL Action.  Please let us know if you still aren't able to use the latest bundle.

**Comment by mirabilos** [comment]
Henry Mercer dixit:

>Hi @mirabilos — this fix was released in version
>[2.2.6](https://github.com/github/codeql-action/releases/tag/v2.2.6) of
>the CodeQL Action. Please let us know if you still aren't able to use
>the latest bundle.

Hm, where did you even get this release from?

https://github.com/github/codeql-action/releases does not show it,
and it shows codeql-bundle-20230317 as latest version, which is what
the GHA updater upgrades to then, for example:

{ 
  "jobs": {
    "analyse": {
      "steps": [
[…]
        { 
          "name": "Initialise CodeQL",
          "uses": ***@***.***",
          "with": {
            "languages": "cpp"
          }
        },
[…]

So v2.2.6 does not look like a real release?


[GHA updater] → https://github.com/saadmk11/github-actions-version-updater

bye,
//mirabilos
-- 
„Cool, /usr/share/doc/mksh/examples/uhr.gz ist ja ein Grund,
mksh auf jedem System zu installieren.“
	-- XTaran auf der OpenRheinRuhr, ganz begeistert
(EN: “[…]uhr.gz is a reason to install mksh on every system.”)

**Comment by henrymercer** [comment]
We release the CodeQL Action using [git tags](https://github.com/github/codeql-action/tags), and release CodeQL Action Bundles using GitHub Releases.  It looks like the tool you're using is only picking up on the GitHub Releases.  We'd recommend configuring your workflow to use the v2 tag (for example `uses: github/codeql-action/init@v2`).  We update this tag with each release.

**Pull request merged**
