### PR TITLE
Update integration test pack versions

### PR DESCRIPTION
**Pull request by aeisenberg**
### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Review by edoardopirovano — APPROVED** [review]
As a very temporary fix to unbreak the tests this seems okay, but we definitely need a more permanent solution that doesn't require us to keep manually bumping versions.

**Comment by aeisenberg** [comment]
> I forced the failing tests to use the nightly build. Now they are passing.

In retrospect, this is misleading. I wasn't implying that this is a _good_ solution, or even something I'd like to commit. I'm planning on working on this tomorrow and finding out what is happening, because upgrades _should_ work.

@edoardopirovano as you said, this would only be temporary. If you are being blocked by failing builds, then it is ok to merge. But, I would prefer to explore deeper when I am able to.

**Comment by edoardopirovano** [comment]
Agree that we should investigate why the upgrades aren't working. I'm not blocked on failing tests, so okay to not merge this and instead wait until we have a proper solution.

**Comment by aeisenberg** [comment]
The 0.1.0 versions fail because the queries are too new and upgrades are not found. The bug is that we haven't updated `codeql resolve upgrades` to work with packs yet. 

I'll work on this next.

**Comment by aeisenberg** [comment]
These tests will not be properly fixed until the next release of the CLI. This is because database upgrades is not yet package-aware. I'll fix that shortly, but it won't be available until the release.

**Comment by aeisenberg** [comment]
Building a new nightly version of the CLI. I expect that once that version is available to the action, then this PR will pass and we can get the action back on track.

**Comment by aeisenberg** [comment]
This latest version hard-codes the tools bundle being used by the packaging integration tests. This will work for now. However, we need to make sure that the version that is pointed to is not cleaned up by automation.

**Comment by aeisenberg** [comment]
I made sure that the release is not cleaned up by automation by making it a non-prerelease. Now, it will always show on top of the releases list, which always keeps the 10 latest.

**Pull request merged**
