### PR TITLE
Add the --threads config option to finalize db

### PR DESCRIPTION
**Pull request by aeisenberg**
This flag is already being used for `runQueries`, so let's use it for
finalize as well.

### Merge / deployment checklist

- [ ] Confirm this change is backwards compatible with existing workflows.
- [ ] Confirm the [readme](https://github.com/github/codeql-action/blob/master/README.md) has been updated if necessary.

### CODE REVIEW

**Comment by aeisenberg** [comment]
I have not updated the README yet. I'll handle that soon. Also, any sort of unit tests or integration tests I should be adding or updating?

**Comment by aeisenberg** [comment]
Also, there's a failing `Integration Testing / runner-upload-sarif`. I don't understand why.

**Comment by robertbrignull** [comment]
> Also, there's a failing `Integration Testing / runner-upload-sarif`. I don't understand why.

That's because you opened your PR from a fork and so the actions token doesn't have write scopes. You can just ignore the failure for this PR.

**Review by robertbrignull — APPROVED** [review]
I see no problem with this. I trust you that passing this flag to this command makes sense.

No need to update the readme or tests for this change. If the existing integration tests pass then that should be enough.

**Comment by aeisenberg** [comment]
Thanks! Will resolve conflicts and rebase.

**Pull request merged**
