### PR TITLE
Create publish-immutable-action workflow

### PR DESCRIPTION
**Pull request by aeisenberg**
This PR creates a workflow that will publish an immutable action whenever a CodeQL Action release is created. We need to distinguish this from CodeQL Bundle releases to ensure that only the appropriate releases trigger the publishing process.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Comment by aeisenberg** [comment]
Don't merge yet. I want to make sure the release workflow is working properly first.

**Comment by aeisenberg** [comment]
@Jcambass, could you take a look to make sure this will be sufficient for immutable actions?

**Comment by aeisenberg** [comment]
Failures unrelated.

**Review by Jcambass — APPROVED** [review]
Looks good!

We'll have to look into manually migrating the existing releases as well.

I will check on that and get back to you.

**Pull request merged**
