### PR TITLE
Remove some dead code

### PR DESCRIPTION
**Pull request by henrymercer**
The Action requires GHES 3.3, so we can safely remove this fallback logic for GHES 2.22 and GHES 3.0.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Review by aeisenberg — COMMENTED** [review]
Looks like `GITHUB_ACTION_REPOSITORY` is not being set during the integration tests. See:

https://github.com/github/codeql-action/actions/runs/3532744788/jobs/5927496032#step:4:14

**Comment by aeisenberg** [comment]
Otherwise looks reasonable.

**Comment by henrymercer** [comment]
So `GITHUB_ACTION_REPOSITORY` is only set when calling an Action from another repository.  We still need to populate it manually if we're running locally.

I've updated the PR to only remove the code that deals with the fact that GHES 2.22 didn't populate `GITHUB_ACTION_REPOSITORY` even when the Action is called from anothe repository.

**Review by aeisenberg — APPROVED** [review]
LGTM assuming all jobs pass.

**Pull request merged**
