### PR TITLE
Stop setting `CODEQL_RUNNER` environment variable if CLI already sets it

### PR DESCRIPTION
**Pull request by angelapwen**
We are now setting the `CODEQL_RUNNER` environment variable in the `codeql database init` step (see backlinked internal PR), so for versions of the CLI that support this feature, we can stop setting it in the Action.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Comment by angelapwen** [comment]
Hm...

```
Deleting failed SARIF upload
  In test mode, therefore deleting the failed analysis to avoid impacting tool status for the Action repository. SARIF ID to delete: 3146eec2-b0d6-11ee-9ed6-a261d13cdc7d.
  Analysis ID to delete: 160977804.
Error: Failed to delete uploaded SARIF analysis. Reason: Error: HttpError: Resource not accessible by integration
```

Odd as we have not changed anything about our token permissions between this PR and the last run. Also, our `PUT` calls to the `analysis` and `analysis/status` endpoints are working, so we should still have the necessary `security_events:write` permissions for a `DELETE` (https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#delete-a-code-scanning-analysis-from-a-repository)

**Comment by aeisenberg** [comment]
That is odd. Maybe try re-running just in case that was a fluke.

**Comment by angelapwen** [comment]
I had re-run it on a previous commit too, probably have 5 total consecutive runs failing now 🤔 might be some kind of API error but odd that it's not hit on any of the other times we're hitting code scanning endpoints.

**Comment by henrymercer** [comment]
I think the "Submit SARIF after failure" check doesn't work on forks — we need to update it so it doesn't try to delete the SARIF when running from a fork.  I've backlinked an internal issue.

**Comment by aeisenberg** [comment]
Is this failing on main, too?

**Comment by aeisenberg** [comment]
Is this failing on main, too?

**Comment by aeisenberg** [comment]
Right... I forgot about that.

**Review by aeisenberg — APPROVED** [review]
LGTM

**Comment by angelapwen** [comment]
> I think the "Submit SARIF after failure" check doesn't work on forks — we need to update it so it doesn't try to delete the SARIF when running from a fork. I've backlinked an internal issue.

Oh shoot I also forgot about that. Thanks!

**Comment by angelapwen** [comment]
I'm going to remove it from being `Required` until we have that backlinked issue done.

**Pull request merged**
