### PR TITLE
Validate workflow within new log group

### PR DESCRIPTION
**Pull request by henrymercer**
This cleans up the logs for `init`.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Review by angelapwen — DISMISSED** [review]
🚢

**Comment by angelapwen** [comment]
Although this seems to come out empty — I wonder if that's confusing to users? Does it need to run in debug mode to actually show something in the group? 

Screenshot 2023-10-26 at 10 17 11 AM

**Comment by henrymercer** [comment]
> Although this seems to come out empty — I wonder if that's confusing to users? Does it need to run in debug mode to actually show something in the group?

Our test workflows are a little unusual since they don't have the typical `languages` matrix configuration.  Therefore we're not seeing the CodeQL CLI logs for `codeql resolve languages`, since that validation isn't being called.

I think the best way to address this is to add a log that no issues were detected.

**Review by angelapwen — APPROVED** [review]
Looks good 👍

**Pull request merged**
