### PR TITLE
Correct the no code found URL

### PR DESCRIPTION
**Pull request by peternewman**
### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Comment by peternewman** [comment]
Also someone with the right access should fix this too (I can't see the instructions, unsurprisingly):
https://github.com/github/docs/blob/356dea8ed4a7e2720df173d7983b02313a9a4a26/content/code-security/code-scanning/troubleshooting-code-scanning/no-source-code-seen-during-build.md?plain=1#L14

**Comment by angelapwen** [comment]
Everything looks good, you'll just need to run the build command again to regenerate the transpiled files to pass the failing PR check! 

`npm run build`  run on the root directory should give you some file changes ✨

**Comment by peternewman** [comment]
Do you want a changelog entry for this? 
>     * [ ]  Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

> Thank you for your contribution @peternewman! The repository uses TypeScript transpiled into Javascript

Oops, I think I'd found that first during the code search, then edited the wrong file!

> We'll look into updating the link in the official documentation as well — thanks again :sparkling_heart:

Excellent thanks.

> Hello! I've just been reminded that we are using a new shortlink — https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build (the one referenced in the documentation) — which will allow us to avoid this problem in the future, as the link will handle the case where the docs URL changes in the future. Do you mind updating to this link as well? Thanks!

Even better!

> Everything looks good, you'll just need to run the build command again to regenerate the transpiled files to pass the failing PR check!

Yeah I was just waiting until I was in front of a proper machine not just doing it in a web browser!

**Comment by angelapwen** [comment]
The failing checks are unrelated to your PR. We'll work on resolving them, please hold tight 😄

**Comment by peternewman** [comment]
It looks like it's all green now @angelapwen 

Perhaps you should have enabled automerge! :smile:

**Comment by angelapwen** [comment]
Ha, I was thinking that perhaps you'd want the pleasure of clicking the merge button 😆 I'll merge now! Thank you again 💖

**Comment by peternewman** [comment]
> Ha, I was thinking that perhaps you'd want the pleasure of clicking the merge button laughing I'll merge now! Thank you again sparkling_heart

I don't think I remember seeing it, and I don't think I'd expect to unless you've given me more rights to the repo than a normal user.

**Pull request merged**
