### PR TITLE
Dependabot alerts for shield only

### PR DESCRIPTION
**Pull request by aeisenberg**

### CODE REVIEW

**Review by angelapwen — APPROVED** [review]
Great!

**Comment by henrymercer** [comment]
I suspect `@github/codeql-action-reviewers` will still be notified as CODEOWNERS, but this still makes sense as we want to notify the production shield even if they don't happen to be in `@github/codeql-action-reviewers`.

**Review by henrymercer — COMMENTED** [review]
I suspect `@github/codeql-action-reviewers` will still be notified as CODEOWNERS, but this still makes sense as we want to notify the production shield even if they don't happen to be in `@github/codeql-action-reviewers`.

**Comment by angelapwen** [comment]
Yep! https://github.com/github/codeql-action/pull/2078

**Pull request merged**
