### PR TITLE
Add names to all pr-checks

### PR DESCRIPTION
**Pull request by aeisenberg**
Small change to aid with debugging failing jobs. I tried to put the most important part of the name of each job first.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Review by adityasharad — APPROVED** [review]
Maybe JavaScript -> JS and CSharp -> C# for brevity. Other than that LGTM.

**Comment by adityasharad** [comment]
...and we have to update our branch protection rules 😆

**Comment by aeisenberg** [comment]
> Maybe JavaScript -> JS and CSharp -> C# for brevity. Other than that LGTM.

Good call. Done.

**Comment by aeisenberg** [comment]
> ...and we have to update our branch protection rules 😆

That's not a PR, though, is it?

**Comment by aeisenberg** [comment]
Odd...does not seem to be showing the new names.

**Comment by edoardopirovano** [comment]
I think automerge won't work due to the checks changing name?

**Comment by aeisenberg** [comment]
Going to need this PR to be force-pushed. It is getting confused because it is expecting all check names to pass, when they no longer exist.

**Pull request merged**
