### PR TITLE
Include workflow queries in status report

### PR DESCRIPTION
**Pull request by robertbrignull**
I realised that queries from the workflow were not being included in the status report from the init action.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/master/README.md) has been updated if necessary.

### CODE REVIEW

**Review by sampart — APPROVED** [review]
👍

**Comment by robertbrignull** [comment]
Thanks for the review. I'm going to add some quick tests of this if I caan work out a good way to do it. Should be all test code though so less of a need to re-review unless you want to. Let me know.

**Comment by sampart** [comment]
I'd like to take a look, but you can merge prior to my re-review. Thanks

**Comment by robertbrignull** [comment]
Unfortunately writing a unit test that creates a status report is quite a pain at the moment because it relies on lots of state. We should work towards making this easier, but right now I'm not sure it's worth it for this change.
I'm running some manual tests now and I'll check that the status reports show up correctly at the other end.

**Pull request merged**
