### PR TITLE
README: document cron fields in example

### PR DESCRIPTION
**Pull request by thaJeztah**
Because I always have to look up the fields, so may as well document it in the example 😅 

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/master/README.md) has been updated if necessary.

### CODE REVIEW

**Review by cbraynor — APPROVED** [review]

**Comment by cbraynor** [comment]
Thank you for suggesting this - crontab fields are sometimes 0-based and sometimes 1-based and it can be difficult to remember which are which. I made the slight adjustment of matching the current Actions documentation for consistency.

**Comment by thaJeztah** [comment]
Thanks! Wondering; I originally came to this repo, looking for the template that's used when you add this action to your repository; is that in a public repository, or somewhere private?

**Comment by cbraynor** [comment]
The specific template is somewhere private as it changes based on a few factors - e.g. languages detected, names of branches, etc. but is very much based off the one in the [README](https://github.com/github/codeql-action#usage). Does the one in this repo meet your needs or are you e.g. looking to suggest these changes there too?

**Comment by thaJeztah** [comment]
Yes, my initial intent was to include this hint in the template 😅
But no problem; just wanted to check if I looked in the right place 👍

**Pull request merged**
