### PR TITLE
Bump minimum CodeQL bundle version to 2.6.3

### PR DESCRIPTION
**Pull request by henrymercer**
Now that GHES 3.2 is deprecated, we can clean up a bunch of tech debt in the Action by bumping our minimum CodeQL Bundle version to 2.6.3, the first version that went into GHES 3.3.

The highlight here is that the Action no longer needs to count lines of code itself, since now all supported versions of the CLI can do that.  This allows us to remove a bunch of code and 14 dependencies!

### Merge / deployment checklist

- [ ] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

**Comment by adityasharad** [comment]
Our docs for direct CodeQL CLI use recommend CodeQL 2.6.3 even for GHES 3.1 and 3.2, so this bump is acceptable even if we have a few customers gradually upgrading from deprecated GHES versions.

**Comment by henrymercer** [comment]
All checks have passed.  The PR isn't green yet since it updates the checks to use newer bundle versions.

**Review by aeisenberg — APPROVED** [review]
Change looks good. Nice to get rid of some code. Looks like there are some merge conflicts now, though.

**Comment by henrymercer** [comment]
Resolved conflicts by rerunning the workflow generator and rebuilding the Action.

**Review by aeisenberg — APPROVED** [review]
#dead-code-society

**Review by aeisenberg — APPROVED** [review]

**Pull request merged**
