### PR TITLE
Send tool names to upload endpoint

### PR DESCRIPTION
**Pull request by kevinsawicki**
This pull request sends an array of all the tool names included in the sarif files to the upload endpoint.

### Merge / deployment checklist

- Run test builds as necessary. Can be on this repository or elsewhere as needed in order to test the change - please include links to tests in otehr repos!
  - [ ] CodeQL using init/finish actions
  - [ ] 3rd party tool using upload action
- [ ] Confirm this change is backwards compatible with existing workflows.
- [ ] Confirm the [readme](https://github.com/github/codeql-action/blob/master/README.md) has been updated if necessary.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
> Implementation LGTM but I think this PR is missing the file with the new tests

Thanks for mentioning that, I've pushed it up now 👍

**Comment by kevinsawicki** [comment]
@robertbrignull should I target `v1` or `master` with this pull request?

**Comment by robertbrignull** [comment]
Target `master` for now. I believe the plan is to merge into `v1` periodically.

**Comment by robertbrignull** [comment]
What tests have you run? Did you try with a third party tool or with an upload that contains multiple tools?

I'll start a run on https://github.com/Anthophila/test-electron as that should try all those options.

**Comment by kevinsawicki** [comment]
> Run test builds as necessary

Apologies I misread this as CI passes, not manual tests.

**Comment by robertbrignull** [comment]
I thought the sast-scan action uploaded multiple files but unfortuantely it doesn't. I'm adding a new workflow to that repo that runs multiple tools. You can see it at https://github.com/Anthophila/test-electron/runs/630193543?check_suite_focus=true
If that's green then I'm totally happy with this PR.

**Comment by robertbrignull** [comment]
I had to reduce the number of tools because it wasn't finishing, but I got a run to succeed: https://github.com/Anthophila/test-electron/runs/630367911?check_suite_focus=true
So this PR is good to go from my point of view.

**Comment by kevinsawicki** [comment]
> I had to reduce the number of tools because it wasn't finishing, but I got a run to succeed:

Thanks for confirming, merging 👍

**Pull request merged**
